// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: mapreduce.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TaskNone   TaskType = 0
	TaskType_TaskMap    TaskType = 1
	TaskType_TaskReduce TaskType = 2
	TaskType_TaskExit   TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TaskNone",
		1: "TaskMap",
		2: "TaskReduce",
		3: "TaskExit",
	}
	TaskType_value = map[string]int32{
		"TaskNone":   0,
		"TaskMap":    1,
		"TaskReduce": 2,
		"TaskExit":   3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapreduce_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_mapreduce_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{0}
}

type GetTaskArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskArgs) Reset() {
	*x = GetTaskArgs{}
	mi := &file_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskArgs) ProtoMessage() {}

func (x *GetTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskArgs.ProtoReflect.Descriptor instead.
func (*GetTaskArgs) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskArgs) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskType               `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.proto.TaskType" json:"type,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ReduceId      int32                  `protobuf:"varint,3,opt,name=reduce_id,json=reduceId,proto3" json:"reduce_id,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	NMap          int32                  `protobuf:"varint,5,opt,name=n_map,json=nMap,proto3" json:"n_map,omitempty"`
	NReduce       int32                  `protobuf:"varint,6,opt,name=n_reduce,json=nReduce,proto3" json:"n_reduce,omitempty"`
	JobId         string                 `protobuf:"bytes,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PluginPath    string                 `protobuf:"bytes,8,opt,name=plugin_path,json=pluginPath,proto3" json:"plugin_path,omitempty"`
	MapSymbol     string                 `protobuf:"bytes,9,opt,name=map_symbol,json=mapSymbol,proto3" json:"map_symbol,omitempty"`
	ReduceSymbol  string                 `protobuf:"bytes,10,opt,name=reduce_symbol,json=reduceSymbol,proto3" json:"reduce_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReply) Reset() {
	*x = GetTaskReply{}
	mi := &file_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReply) ProtoMessage() {}

func (x *GetTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReply.ProtoReflect.Descriptor instead.
func (*GetTaskReply) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskReply) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TaskNone
}

func (x *GetTaskReply) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *GetTaskReply) GetReduceId() int32 {
	if x != nil {
		return x.ReduceId
	}
	return 0
}

func (x *GetTaskReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetTaskReply) GetNMap() int32 {
	if x != nil {
		return x.NMap
	}
	return 0
}

func (x *GetTaskReply) GetNReduce() int32 {
	if x != nil {
		return x.NReduce
	}
	return 0
}

func (x *GetTaskReply) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetTaskReply) GetPluginPath() string {
	if x != nil {
		return x.PluginPath
	}
	return ""
}

func (x *GetTaskReply) GetMapSymbol() string {
	if x != nil {
		return x.MapSymbol
	}
	return ""
}

func (x *GetTaskReply) GetReduceSymbol() string {
	if x != nil {
		return x.ReduceSymbol
	}
	return ""
}

type ReportTaskArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskType               `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.proto.TaskType" json:"type,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ReduceId      int32                  `protobuf:"varint,3,opt,name=reduce_id,json=reduceId,proto3" json:"reduce_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	WorkerId      string                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskArgs) Reset() {
	*x = ReportTaskArgs{}
	mi := &file_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskArgs) ProtoMessage() {}

func (x *ReportTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskArgs.ProtoReflect.Descriptor instead.
func (*ReportTaskArgs) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *ReportTaskArgs) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TaskNone
}

func (x *ReportTaskArgs) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ReportTaskArgs) GetReduceId() int32 {
	if x != nil {
		return x.ReduceId
	}
	return 0
}

func (x *ReportTaskArgs) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskArgs) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type ReportTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskReply) Reset() {
	*x = ReportTaskReply{}
	mi := &file_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskReply) ProtoMessage() {}

func (x *ReportTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskReply.ProtoReflect.Descriptor instead.
func (*ReportTaskReply) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{3}
}

type RunningTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskType               `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.proto.TaskType" json:"type,omitempty"`
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningTask) Reset() {
	*x = RunningTask{}
	mi := &file_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTask) ProtoMessage() {}

func (x *RunningTask) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTask.ProtoReflect.Descriptor instead.
func (*RunningTask) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *RunningTask) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TaskNone
}

func (x *RunningTask) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type HeartbeatArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Running       []*RunningTask         `protobuf:"bytes,3,rep,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatArgs) Reset() {
	*x = HeartbeatArgs{}
	mi := &file_mapreduce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatArgs) ProtoMessage() {}

func (x *HeartbeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatArgs.ProtoReflect.Descriptor instead.
func (*HeartbeatArgs) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatArgs) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatArgs) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatArgs) GetRunning() []*RunningTask {
	if x != nil {
		return x.Running
	}
	return nil
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Renewed       int32                  `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_mapreduce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatReply) GetRenewed() int32 {
	if x != nil {
		return x.Renewed
	}
	return 0
}

var File_mapreduce_proto protoreflect.FileDescriptor

const file_mapreduce_proto_rawDesc = "" +
	"\n" +
	"\x0fmapreduce.proto\x12\trpc.proto\"*\n" +
	"\vGetTaskArgs\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xb3\x02\n" +
	"\fGetTaskReply\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.rpc.proto.TaskTypeR\x04type\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12\x1b\n" +
	"\treduce_id\x18\x03 \x01(\x05R\breduceId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x13\n" +
	"\x05n_map\x18\x05 \x01(\x05R\x04nMap\x12\x19\n" +
	"\bn_reduce\x18\x06 \x01(\x05R\anReduce\x12\x15\n" +
	"\x06job_id\x18\a \x01(\tR\x05jobId\x12\x1f\n" +
	"\vplugin_path\x18\b \x01(\tR\n" +
	"pluginPath\x12\x1d\n" +
	"\n" +
	"map_symbol\x18\t \x01(\tR\tmapSymbol\x12#\n" +
	"\rreduce_symbol\x18\n" +
	" \x01(\tR\freduceSymbol\"\xa4\x01\n" +
	"\x0eReportTaskArgs\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.rpc.proto.TaskTypeR\x04type\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12\x1b\n" +
	"\treduce_id\x18\x03 \x01(\x05R\breduceId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\"\x11\n" +
	"\x0fReportTaskReply\"O\n" +
	"\vRunningTask\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.rpc.proto.TaskTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\"u\n" +
	"\rHeartbeatArgs\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x120\n" +
	"\arunning\x18\x03 \x03(\v2\x16.rpc.proto.RunningTaskR\arunning\"*\n" +
	"\x0eHeartbeatReply\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\x05R\arenewed*C\n" +
	"\bTaskType\x12\f\n" +
	"\bTaskNone\x10\x00\x12\v\n" +
	"\aTaskMap\x10\x01\x12\x0e\n" +
	"\n" +
	"TaskReduce\x10\x02\x12\f\n" +
	"\bTaskExit\x10\x032\xce\x01\n" +
	"\tMapReduce\x12:\n" +
	"\aGetTask\x12\x16.rpc.proto.GetTaskArgs\x1a\x17.rpc.proto.GetTaskReply\x12C\n" +
	"\n" +
	"ReportTask\x12\x19.rpc.proto.ReportTaskArgs\x1a\x1a.rpc.proto.ReportTaskReply\x12@\n" +
	"\tHeartbeat\x12\x18.rpc.proto.HeartbeatArgs\x1a\x19.rpc.proto.HeartbeatReplyB\x1cZ\x1amapreduce/pkg/rpc/pb;rpcpbb\x06proto3"

var (
	file_mapreduce_proto_rawDescOnce sync.Once
	file_mapreduce_proto_rawDescData []byte
)

func file_mapreduce_proto_rawDescGZIP() []byte {
	file_mapreduce_proto_rawDescOnce.Do(func() {
		file_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapreduce_proto_rawDesc), len(file_mapreduce_proto_rawDesc)))
	})
	return file_mapreduce_proto_rawDescData
}

var file_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mapreduce_proto_goTypes = []any{
	(TaskType)(0),           // 0: rpc.proto.TaskType
	(*GetTaskArgs)(nil),     // 1: rpc.proto.GetTaskArgs
	(*GetTaskReply)(nil),    // 2: rpc.proto.GetTaskReply
	(*ReportTaskArgs)(nil),  // 3: rpc.proto.ReportTaskArgs
	(*ReportTaskReply)(nil), // 4: rpc.proto.ReportTaskReply
	(*RunningTask)(nil),     // 5: rpc.proto.RunningTask
	(*HeartbeatArgs)(nil),   // 6: rpc.proto.HeartbeatArgs
	(*HeartbeatReply)(nil),  // 7: rpc.proto.HeartbeatReply
}
var file_mapreduce_proto_depIdxs = []int32{
	0, // 0: rpc.proto.GetTaskReply.type:type_name -> rpc.proto.TaskType
	0, // 1: rpc.proto.ReportTaskArgs.type:type_name -> rpc.proto.TaskType
	0, // 2: rpc.proto.RunningTask.type:type_name -> rpc.proto.TaskType
	5, // 3: rpc.proto.HeartbeatArgs.running:type_name -> rpc.proto.RunningTask
	1, // 4: rpc.proto.MapReduce.GetTask:input_type -> rpc.proto.GetTaskArgs
	3, // 5: rpc.proto.MapReduce.ReportTask:input_type -> rpc.proto.ReportTaskArgs
	6, // 6: rpc.proto.MapReduce.Heartbeat:input_type -> rpc.proto.HeartbeatArgs
	2, // 7: rpc.proto.MapReduce.GetTask:output_type -> rpc.proto.GetTaskReply
	4, // 8: rpc.proto.MapReduce.ReportTask:output_type -> rpc.proto.ReportTaskReply
	7, // 9: rpc.proto.MapReduce.Heartbeat:output_type -> rpc.proto.HeartbeatReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mapreduce_proto_init() }
func file_mapreduce_proto_init() {
	if File_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapreduce_proto_rawDesc), len(file_mapreduce_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapreduce_proto_goTypes,
		DependencyIndexes: file_mapreduce_proto_depIdxs,
		EnumInfos:         file_mapreduce_proto_enumTypes,
		MessageInfos:      file_mapreduce_proto_msgTypes,
	}.Build()
	File_mapreduce_proto = out.File
	file_mapreduce_proto_goTypes = nil
	file_mapreduce_proto_depIdxs = nil
}
